"""Final Fix

Revision ID: c3d0a2e0da47
Revises: ad7675225fbc
Create Date: 2026-02-04 11:21:19.629467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3d0a2e0da47'
down_revision: Union[str, Sequence[str], None] = 'ad7675225fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_workspaces', sa.Column('admin_email', sa.String(), nullable=False))
    op.add_column('access_workspaces', sa.Column('admin_full_name', sa.String(), nullable=False))
    op.add_column('access_workspaces', sa.Column('status', sa.String(), nullable=False))
    op.add_column('access_workspaces', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('access_workspaces', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('access_workspaces', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.alter_column('access_workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_workspaces', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('access_workspaces', 'suspended_at')
    op.drop_column('access_workspaces', 'activated_at')
    op.drop_column('access_workspaces', 'settings')
    op.drop_column('access_workspaces', 'status')
    op.drop_column('access_workspaces', 'admin_full_name')
    op.drop_column('access_workspaces', 'admin_email')
    # ### end Alembic commands ###
